# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set env
        run: echo "RELEASE_NUMBER=${GITHUB_RUN_NUMBER}" >> GITHUB_ENV
        
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_latest . 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django__${{ env.RELEASE_NUMBER }} .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django__${{ env.RELEASE_NUMBER }}

      - name: Deploy
        uses: safe2008/eks-actions@v0.0.4
        env:
          aws_access_key_id: ${{ secrets.AWS_KEYID }}
          aws_secret_access_key: ${{ secrets.AWS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        with:
          args: | 
            kubectl rollout restart deployment/was
            aws s3 cp Dockerfile s3://${{ secrets.BUCKET_NAME }}/${{ github.run_number }}
