name: CICD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_latest . 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_${GITHUB_RUN_NUMBER} .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd:django_${GITHUB_RUN_NUMBER}

      - name: Deploy
        uses: safe2008/eks-actions@v0.0.4
        env:
          aws_access_key_id: ${{ secrets.AWS_KEYID }}
          aws_secret_access_key: ${{ secrets.AWS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        with:
          args: | 
            kubectl rollout restart deployment/was -n was-ns

